# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130_8pM_AHKADbHO3inbb9CQmA89jeVup
"""

import requests
import json
from pprint import pprint

from google import genai

client = genai.Client(api_key="AIzaSyCaso9wrJrhGe-uWWO7Azdgc6uevt2BGqw")

while True:
    question = input("How can I help you?\n")

    if question.lower() in ["quit", "exit"]:
        break

    response = client.models.generate_content(
        model="gemini-3-pro-preview",
        contents=question
    )

    print(response.text)